version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: notes_db
    env_file: .env
    environment:
      # The MySQL image uses these to bootstrap DB and user on first run.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    container_name: notes_web
    env_file: .env
    ports:
      - "8088:5000"   # host:container
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:5000/healthz').getcode()==200 else sys.exit(1)"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data:
